(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition max_stack_depth : int := 20000.

Definition check_stack (stack : int) : unit :=
  if CoqOfOCaml.Stdlib.le stack 0 then
    Stdlib.raise (Build_extensible "Out_of_stack" unit tt)
  else
    tt.

Definition check_gas (gas : Lambda_vm.Gas.t) : unit :=
  if Lambda_vm.Gas.is_empty gas then
    Stdlib.raise (Build_extensible "Out_of_gas" unit tt)
  else
    tt.
