(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition t : Set := Stdlib.ref int.

Definition constant_burn : int := 100.

Definition log2_burn (cardinality : int) : int :=
  let log2_cardinality :=
    Stdlib.Float.to_int
      (Stdlib.Float.ceil (Stdlib.Float.log2 (Stdlib.Float.of_int cardinality)))
    in
  Z.add constant_burn (Z.mul constant_burn log2_cardinality).

Definition make {A : Set} (initial_gas : A) : Stdlib.ref A :=
  Stdlib.ref_value initial_gas.

Definition is_empty (t_value : Stdlib.ref int) : bool :=
  CoqOfOCaml.Stdlib.le (Stdlib.op_exclamation t_value) 0.

Definition burn (t_value : Stdlib.ref int) (amount : int) : unit :=
  Stdlib.op_coloneq t_value (Z.sub (Stdlib.op_exclamation t_value) amount).

Definition burn_constant (t_value : Stdlib.ref int) : unit :=
  burn t_value constant_burn.

Definition burn_log2 (t_value : Stdlib.ref int) (cardinality : int) : unit :=
  burn t_value (log2_burn cardinality).
