(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition t : Set := int.

Definition compare : int -> int -> int := Stdlib.Int.compare.

Definition initial : int := 0.

Definition next (t_value : int) : int := Z.add t_value 1.

Definition to_string : int -> string := CoqOfOCaml.Stdlib.string_of_int.

Definition pp (fmt : Stdlib.Format.formatter) (t_value : int) : unit :=
  Stdlib.Format.pp_print_string fmt (to_string t_value).
