import * as fc from 'fast-check';
import { createCookieBaker } from '../src/state';

export const cookieBakerArbitrary = () =>
    fc.tuple(fc.integer({ min: 0, max: 2000000000 }),
        fc.integer({ min: 0, max: 200 }),
        fc.integer({ min: 0, max: 200 }),
        fc.integer({ min: 0, max: 200 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
        fc.integer({ min: 0, max: 10 }),
    ).map(
        ([numberOfCookie,
            numberOfCursor,
            numberOfGrandma,
            numberOfFarm,
            numberOfMine,
            numberOfFactory,
            numberOfBank,
            numberOfTemple,
            numberOfWizard,
            numberOfShipment,
            numberOfAlchemy,
            numberOfPortal,
            numberOfTimeMachine,
            numberOfAntimatter,
            numberOfPrism,
            numberOfChanceMaker,
            numberOfFractal,
            numberOfJavaScript,
            numberOfIdleverse,
            numberOfCordex,
            numberOfFreeCursor,
            numberOfFreeGrandma,
            numberOfFreeFarm,
            numberOfFreeMine,
            numberOfFreeFactory,
            numberOfFreeBank,
            numberOfFreeTemple,
            numberOfFreeWizard,
            numberOfFreeShipment,
            numberOfFreeAlchemy,
            numberOfFreePortal,
            numberOfFreeTimeMachine,
            numberOfFreeAntimatter,
            numberOfFreePrism,
            numberOfFreeChanceMaker,
            numberOfFreeFractal,
            numberOfFreeJavaScript,
            numberOfFreeIdleverse,
            numberOfFreeCordex,
        ]) => {
            const cookie_baker = createCookieBaker(
                numberOfCookie,
                numberOfCursor,
                numberOfGrandma,
                numberOfFarm,
                numberOfMine,
                numberOfFactory,
                numberOfBank,
                numberOfTemple,
                numberOfWizard,
                numberOfShipment,
                numberOfAlchemy,
                numberOfPortal,
                numberOfTimeMachine,
                numberOfAntimatter,
                numberOfPrism,
                numberOfChanceMaker,
                numberOfFractal,
                numberOfJavaScript,
                numberOfIdleverse,
                numberOfCordex,

                numberOfFreeCursor,
                numberOfFreeGrandma,
                numberOfFreeFarm,
                numberOfFreeMine,
                numberOfFreeFactory,
                numberOfFreeBank,
                numberOfFreeTemple,
                numberOfFreeWizard,
                numberOfFreeShipment,
                numberOfFreeAlchemy,
                numberOfFreePortal,
                numberOfFreeTimeMachine,
                numberOfFreeAntimatter,
                numberOfFreePrism,
                numberOfFreeChanceMaker,
                numberOfFreeFractal,
                numberOfFreeJavaScript,
                numberOfFreeIdleverse,
                numberOfFreeCordex,
            )
            return cookie_baker;
        });