# ./.tmuxinator.yml

name: spawn_validators
root: ./data

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
on_project_start: esy && rm $(find ./ -name state.bin) # Make sure the project is built, and delete any `state.bin`s to ensure we're running from a fresh state
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: command

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t test_nodes

windows:
  - editor:
      layout: tiled
      # Due to an esy bug, multiple `esy x`s can't run at the same time, so we use sleep to space them out
      # Also, we need to add a delay to the first one to give the `on_project_start` command time to run
      panes:
        - sleep 1 && esy x deku-node 0
        - sleep 3 && esy x deku-node 1
        - sleep 5 && esy x deku-node 2
        - sleep 7 && esy x sidecli produce-block 0

