version: "3.8"
services:
  deku-node-0:
    container_name: deku-node-0
    restart: always
    image: ghcr.io/marigold-dev/deku
    expose:
      - 4040
    volumes:
      - ./data/0:/app/data
  deku-node-1:
    container_name: deku-node-1
    restart: always
    image: ghcr.io/marigold-dev/deku
    expose:
      - 4040
    volumes:
      - ./data/1:/app/data
  deku-node-2:
    container_name: deku-node-2
    restart: always
    image: ghcr.io/marigold-dev/deku
    expose:
      - 4040
    volumes:
      - ./data/2:/app/data
