lib: [
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/lib/sidechain/META"
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/lib/sidechain/dune-package"
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/lib/sidechain/opam"
]
bin: [
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/bin/deku-node"
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/bin/sidecli"
]
doc: [
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/doc/sidechain/LICENSE"
  "/home/anchpop/workspaces/deku/_esy/default/store/b/sidechain-fb93e8b6/install/default/doc/sidechain/README.md"
]
