"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cookieBakerArbitrary = void 0;
var fc = require("fast-check");
var state_1 = require("../src/state");
// 77
var cookieBakerArbitrary = function () {
    return fc.tuple(fc.integer({ min: 0, max: 2000000000 }), fc.integer({ min: 0, max: 200 }), fc.integer({ min: 0, max: 200 }), fc.integer({ min: 0, max: 200 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 }), fc.integer({ min: 0, max: 10 })).map(function (_a) {
        var numberOfCookie = _a[0], numberOfCursor = _a[1], numberOfGrandma = _a[2], numberOfFarm = _a[3], numberOfMine = _a[4], numberOfFactory = _a[5], numberOfBank = _a[6], numberOfTemple = _a[7], numberOfWizard = _a[8], numberOfShipment = _a[9], numberOfAlchemy = _a[10], numberOfPortal = _a[11], numberOfTimeMachine = _a[12], numberOfAntimatter = _a[13], numberOfPrism = _a[14], numberOfChanceMaker = _a[15], numberOfFractal = _a[16], numberOfJavaScript = _a[17], numberOfIdleverse = _a[18], numberOfCordex = _a[19], numberOfFreeCursor = _a[20], numberOfFreeGrandma = _a[21], numberOfFreeFarm = _a[22], numberOfFreeMine = _a[23], numberOfFreeFactory = _a[24], numberOfFreeBank = _a[25], numberOfFreeTemple = _a[26], numberOfFreeWizard = _a[27], numberOfFreeShipment = _a[28], numberOfFreeAlchemy = _a[29], numberOfFreePortal = _a[30], numberOfFreeTimeMachine = _a[31], numberOfFreeAntimatter = _a[32], numberOfFreePrism = _a[33], numberOfFreeChanceMaker = _a[34], numberOfFreeFractal = _a[35], numberOfFreeJavaScript = _a[36], numberOfFreeIdleverse = _a[37], numberOfFreeCordex = _a[38];
        var cookie_baker = (0, state_1.createCookieBaker)(numberOfCookie, numberOfCursor, numberOfGrandma, numberOfFarm, numberOfMine, numberOfFactory, numberOfBank, numberOfTemple, numberOfWizard, numberOfShipment, numberOfAlchemy, numberOfPortal, numberOfTimeMachine, numberOfAntimatter, numberOfPrism, numberOfChanceMaker, numberOfFractal, numberOfJavaScript, numberOfIdleverse, numberOfCordex, numberOfFreeCursor, numberOfFreeGrandma, numberOfFreeFarm, numberOfFreeMine, numberOfFreeFactory, numberOfFreeBank, numberOfFreeTemple, numberOfFreeWizard, numberOfFreeShipment, numberOfFreeAlchemy, numberOfFreePortal, numberOfFreeTimeMachine, numberOfFreeAntimatter, numberOfFreePrism, numberOfFreeChanceMaker, numberOfFreeFractal, numberOfFreeJavaScript, numberOfFreeIdleverse, numberOfFreeCordex);
        return cookie_baker;
    });
};
exports.cookieBakerArbitrary = cookieBakerArbitrary;
