export enum actions {
    address = "address",
    incr_Cookie = "cookie",
    incr_Cursor = "cursor",
    incr_Grandma = "grandma",
    incr_Farm = "farm",
    incr_Mine = "mine",
    incr_Factory = "factory",
    incr_Bank = "bank",

    incr_Temple = "temple",
    incr_Wizard = "wizard",
    incr_Shipment = "shipment",
    incr_Alchemy = "alchemy",
    incr_Portal = "portal",
    incr_TimeMachine = "timemachine",
    incr_Antimatter = "antimatter",
    incr_Prism = "prism",
    incr_ChanceMaker = "chancemaker",
    incr_Fractal = "fractal",
    incr_Javascript = "javascript",
    incr_Idleverse = "idleverse",
    incr_Cordex = "cordex",
} 