export enum actions {
    incrementCookie = "cookie",
    incrementCursor = "cursor",
    incrementGrandma = "grandma",
    incrementFarm = "farm",
    incrementMine = "mine",
    incrementFactory = "factory",
    incrementBank = "bank",
    
    incrementTemple = "temple",
    incrementWizard = "wizard",
    incrementShipment = "shipment",
    incrementAlchemy = "alchemy",
    incrementPortal = "portal",
    incrementTimeMachine = "timemachine",
    incrementAntimatter = "antimatter",
    incrementPrism = "prism",
    incrementChanceMaker = "chancemaker",
    incrementFractal = "fractal",
    incrementJavascript = "javascript",
    incrementIdleverse = "idleverse",
    incrementCordex = "cordex",
} 