"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.actions = void 0;
var actions;
(function (actions) {
    actions["incr_Cookie"] = "cookie";
    actions["incr_Cursor"] = "cursor";
    actions["incr_Grandma"] = "grandma";
    actions["incr_Farm"] = "farm";
    actions["incr_Mine"] = "mine";
    actions["incr_Factory"] = "factory";
    actions["incr_Bank"] = "bank";
    actions["incr_Temple"] = "temple";
    actions["incr_Wizard"] = "wizard";
    actions["incr_Shipment"] = "shipment";
    actions["incr_Alchemy"] = "alchemy";
    actions["incr_Portal"] = "portal";
    actions["incr_TimeMachine"] = "timemachine";
    actions["incr_Antimatter"] = "antimatter";
    actions["incr_Prism"] = "prism";
    actions["incr_ChanceMaker"] = "chancemaker";
    actions["incr_Fractal"] = "fractal";
    actions["incr_Javascript"] = "javascript";
    actions["incr_Idleverse"] = "idleverse";
    actions["incr_Cordex"] = "cordex";
})(actions = exports.actions || (exports.actions = {}));
