"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.actions = void 0;
var actions;
(function (actions) {
    actions["incrementCookie"] = "cookie";
    actions["incrementCursor"] = "cursor";
    actions["incrementGrandma"] = "grandma";
    actions["incrementFarm"] = "farm";
    actions["incrementMine"] = "mine";
    actions["incrementFactory"] = "factory";
    actions["incrementBank"] = "bank";
    actions["incrementTemple"] = "temple";
    actions["incrementWizard"] = "wizard";
    actions["incrementShipment"] = "shipment";
    actions["incrementAlchemy"] = "alchemy";
    actions["incrementPortal"] = "portal";
    actions["incrementTimeMachine"] = "timemachine";
    actions["incrementAntimatter"] = "antimatter";
    actions["incrementPrism"] = "prism";
    actions["incrementChanceMaker"] = "chancemaker";
    actions["incrementFractal"] = "fractal";
    actions["incrementJavascript"] = "javascript";
    actions["incrementIdleverse"] = "idleverse";
    actions["incrementCordex"] = "cordex";
})(actions = exports.actions || (exports.actions = {}));
