name: Publish deku-fextesa docker image  

on:
  push:
    branches:
      - "main"
    paths:
      - "deku-fextesa/**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push deku-fextesa
        id: docker_build_deku_flextesa
        uses: docker/build-push-action@v2
        with:
          context: ./deku-fextesa
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/marigold-dev/deku-fextesa:${{ github.sha }}
            ghcr.io/marigold-dev/deku-fextesa:latest
